/*
 * Copyright 2025 SZIGETI János
 *
 * This file is part of Bilis ESP32 Basic, which is released under GNU General Public License.version 3.
 * See LICENSE or <https://www.gnu.org/licenses/> for full license details.
 */

#include <stdbool.h>
#include <string.h>
#include "typeaux.h"
#include "ssd1306.h"

// ============== Defines ==============
#define CMD_SETMUXRATIO   0xA8
#define CMD_SETDISPOFFS   0xD3
#define CMD_SETADDRMODE   0x20
#define CMD_SETCOLRANGE   0x21
#define CMD_SETPAGERANGE  0x22
#define CMD_SETPAGE       0xB0
#define CMD_SETSTARTLINE  0x40  // 0x40 .. 0x7F
#define CMD_SETSEGREMAP   0xA0  // 0xA0 .. 0xA1
#define CMD_SETSCANDIR    0xC0  // 0xC0 | 0xC8
#define CMD_ENTIREDISPON  0xA4
#define CMD_SETDISPON     0xAE
#define CMD_INVERSEDISP   0xA6
#define CMD_SETCOMPINCFG  0xDA
#define CMD_SETCONTRAST   0x81
#define CMD_SETCLKFREQ    0xD5
#define CMD_SETPHASELEN   0xD9

#define MASK_COM 0x3F
#define MASK_SEG 0x7F
#define MASK_PAGE 0x07


// ============== Local types ==============
// ============== Local data ==============

// ============== Internal function declarations ==============

// ============== Implementation ==============
// -------------- Internal functions --------------

// -------------- Interface functions --------------
/**
 * Put control byte into a buffer (into I2C Host-to-Device buffer).
 * @param pu8Dest Where to put the byte(s).
 * @param bContinuate Set continuation bit. True: control byte is followed by a single command/data byte, then another control byte is required.
 * @param bData Control is followed by data (true) or command (false).
 * @return Number of written bytes.
 */
uint8_t ssd1306_ctrl(uint8_t *pu8Dest, bool bContinuate, bool bData) {
  pu8Dest[0] = (bContinuate ? 0x80 : 0) | (bData ? 0x40 : 0);
  return 1;
}

/**
 * Set multiplex ratio.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8Ratio Multiplex ratio - 1. Valid range: 15 -- 63 (DEFAULT).
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_mux_ratio(uint8_t *pu8Dest, uint8_t u8Ratio) {
  pu8Dest[0] = CMD_SETMUXRATIO;
  if (SSD1306_MUX_MAX < u8Ratio) u8Ratio = SSD1306_MUX_MAX;
  if (u8Ratio < SSD1306_MUX_MIN) u8Ratio = SSD1306_MUX_MIN;
  pu8Dest[1] = u8Ratio;
  return 2;
}

/**
 * Set Display horizontal offset.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8Offset Vertical shift of COM_n to Row_n assignment. Value 1 means COM0 is assigned to Row1. Valid range: 0 (DEFAULT) -- 63.
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_display_offset(uint8_t *pu8Dest, uint8_t u8Offset) {
  pu8Dest[0] = CMD_SETDISPOFFS;
  pu8Dest[1] = u8Offset & MASK_COM;
  return 2;
}

/**
 * Set display start line. Multiplex ratio defines how many lines after the start line are still displayed
 * (e.g., if multiplex ratio is 31, and start line is 20, RAM lines [20,52) will be displayed and lines [52,64) and [0,20) will not be displayed).
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8StartLine Amount of vertical shift. Valid range: 0 (DEFAULT) -- 63.
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_display_startline(uint8_t *pu8Dest, uint8_t u8StartLine) {
  pu8Dest[0] = CMD_SETSTARTLINE | (u8StartLine & MASK_COM);
  return 1;
}

/**
 * Set memory addressing mode.
 * @param pu8Dest Where to put the generated byte(s).
 * @param eMode Either horizontal, vertical or page (DEFAULT) addressing mode.
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_memory_addressing_mode(uint8_t *pu8Dest, EAddressingMode eMode) {
  pu8Dest[0] = CMD_SETADDRMODE;
  pu8Dest[1] = (uint8_t)eMode;
  return 2;
}

/**
 * Specifies the addressed column range in horizontal and vertical addressing modes.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8First First column to address (0 (DEFAULT) -- 127).
 * @param u8Last Last column to address (0 -- 127 (DEFAULT)).
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_hv_column_range(uint8_t *pu8Dest, uint8_t u8First, uint8_t u8Last) {
  pu8Dest[0] = CMD_SETCOLRANGE;
  pu8Dest[1] = u8First & MASK_SEG;
  pu8Dest[2] = u8Last & MASK_SEG;
  return 3;
}

/**
 * Specifies the addressed page (i.e., vertical) range in horizontal and vertical addressing modes.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8First First page to address (0 (DEFAULT) -- 7).
 * @param u8Last Last page to address (0 -- 7 (DEFAULT)).
 * @return Number of written bytes.
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_hv_page_range(uint8_t *pu8Dest, uint8_t u8First, uint8_t u8Last) {
  pu8Dest[0] = CMD_SETPAGERANGE;
  pu8Dest[1] = u8First & MASK_PAGE;
  pu8Dest[2] = u8Last & MASK_PAGE;
  return 3;
}

/**
 * In page addressing mode a single page is addressed.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8Page Addressed page (0 -- 7).
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_page_page(uint8_t *pu8Dest, uint8_t u8Page) {
  pu8Dest[0] = CMD_SETPAGE | (u8Page & MASK_PAGE);
  return 1;
}

/**
 * Specifies the horizontal starting position in page addressing mode.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8Start Horizontal position (Column? / Segment?) (0 -- 255(?))
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_page_start_column(uint8_t *pu8Dest, uint8_t u8Start) {
  pu8Dest[0] = 0x00 | (u8Start & 0x0F);
  pu8Dest[1] = 0x10 | ((u8Start >> 4) & 0x0F);
  return 2;
}

/**
 * Specifies whether to remap segments (horizontal flip) or not.
 * @param pu8Dest Where to put the generated byte(s).
 * @param bReverse Do horizontal (left-to-right) flip.
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_segment_remap(uint8_t *pu8Dest, bool bReverse) {
  pu8Dest[0] = CMD_SETSEGREMAP | (bReverse ? 1 : 0);
  return 1;
}

/**
 * Change COM output scan direction immediately (vertical flip).
 * @param pu8Dest Where to put the generated byte(s).
 * @param bReverse Do vertical (upside down).
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_output_scan_dir(uint8_t *pu8Dest, bool bReverse) {
  pu8Dest[0] = CMD_SETSCANDIR | (bReverse ? 8 : 0);
  return 1;
}

/**
 * Set COM to RAM assignment configuration.
 * @param pu8Dest Where to put the generated byte(s).
 * @param bAltPinCfg Alternative COM pin configuration (false: COM 0..31 and COM 32..63 take row (RAM) data sequentially,
 * true: COM 0..31 and COM 32..63 take row (RAM) data interlaced).
 * @param bComLRRemap COM 0..31 and COM 32..63 row / RAM access is swapped.
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_com_pins_hw_config(uint8_t *pu8Dest, bool bAltPinCfg, bool bComLRRemap) {
  pu8Dest[0] = CMD_SETCOMPINCFG;
  pu8Dest[1] = (bAltPinCfg ? 0x10 : 0) | (bComLRRemap? 0x20 : 0) | 0x02;
  return 2;
}

/**
 * Set display contrast.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8Value Contrast (luminance) value (0 .. 255, DEFAULT: 127).
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_contrast_control(uint8_t *pu8Dest, uint8_t u8Value) {
  pu8Dest[0] = CMD_SETCONTRAST;
  pu8Dest[1] = u8Value;
  return 2;
}

/**
 * Switch entire display (every pixel) on.
 * @param pu8Dest Where to put the generated byte(s).
 * @param bOn Switch on (true), display RAM content (false).
 * @return Number of written bytes.
 */
uint8_t ssd1306_entire_display_on(uint8_t *pu8Dest, bool bOn) {
  pu8Dest[0] = CMD_ENTIREDISPON | (bOn ? 1 : 0);
  return 1;
}

/**
 * Set display on.
 * @param pu8Dest Where to put the generated byte(s).
 * @param bOn Display RAM content (true), no display (false).
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_display_on(uint8_t *pu8Dest, bool bOn) {
  pu8Dest[0] = CMD_SETDISPON | (bOn ? 1 : 0);
  return 1;
}

/**
 * Invert display.
 * @param pu8Dest Where to put the generated byte(s).
 * @param bInverse Invert display (true: bits 0 are luminating, false: bits 1 are luminating).
 * @return Number of written bytes.
 */
uint8_t ssd1306_inverse_display(uint8_t *pu8Dest, bool bInverse) {
  pu8Dest[0] = CMD_INVERSEDISP | (bInverse ? 1 : 0);
  return 1;
}

/**
 * Set internal oscilloscope frequency and clock divisor.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8Freq Logical frequency value (0 (lowest) .. 15 (highest), DEFAULT: 8).
 * @param u8Divisor Divisor - 1 (0..15, DEFAULT: 0 (meaning divisor is 1)).
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_display_osc_freq(uint8_t *pu8Dest, uint8_t u8Freq, uint8_t u8Divisor) {
  pu8Dest[0] = CMD_SETCLKFREQ;
  pu8Dest[1] = (u8Divisor & 0x0F) | ((u8Freq & 0x0F) << 4);
  return 2;
}

/**
 * Set pre-charge period lengths.
 * @param pu8Dest Where to put the generated byte(s).
 * @param u8dclkPhase1Len Length of phase 1 (in DCLK, 1..15, DEFAULT: 2)
 * @param u8dclkPhase2Len Length of phase 2 (in DCLK, 1..15, DEFAULT: 2)
 * @return Number of written bytes.
 */
uint8_t ssd1306_set_precharge_period(uint8_t *pu8Dest, uint8_t u8dclkPhase1Len, uint8_t u8dclkPhase2Len) {
  pu8Dest[0] = CMD_SETPHASELEN;
  pu8Dest[1] = (u8dclkPhase1Len & 0x0F) | ((u8dclkPhase2Len & 0x0F) << 4);
  return 2;
}

/**
 * Enable charge pump regulator.
 * @param pu8Dest Where to put the generated byte(s).
 * @param bEnable True: enable charge pump, false: disable charge pump.
 * @return Number of written bytes.
 */
uint8_t ssd1306_charge_pump_setting(uint8_t *pu8Dest, bool bEnable) {
  pu8Dest[0] = 0x8D;
  pu8Dest[1] = 0x10 | (bEnable ? 4 : 0);
  return 2;
}

/**
 * Create SSD1306 initialization sequence (sequence of commands).
 * @param pu8Dest Where to put the generated byte(s).
 * @return Number of written bytes.
 */
uint8_t ssd1306_get_startseq(uint8_t *pu8Dest) {
  uint8_t u8Ret = 0;
  u8Ret += ssd1306_ctrl(pu8Dest, false, false);
  u8Ret += ssd1306_set_mux_ratio(&pu8Dest[u8Ret], SSD1306_MUX_MAX);
  u8Ret += ssd1306_set_display_offset(&pu8Dest[u8Ret], 0x0);
  u8Ret += ssd1306_set_display_startline(&pu8Dest[u8Ret], 0);
  u8Ret += ssd1306_set_memory_addressing_mode(&pu8Dest[u8Ret], SSD1306_ADDR_VERT);
  u8Ret += ssd1306_set_segment_remap(&pu8Dest[u8Ret], false);
  u8Ret += ssd1306_set_output_scan_dir(&pu8Dest[u8Ret], false);
  u8Ret += ssd1306_set_com_pins_hw_config(&pu8Dest[u8Ret], false, false);
  u8Ret += ssd1306_set_contrast_control(&pu8Dest[u8Ret], 0x7F);
  u8Ret += ssd1306_entire_display_on(&pu8Dest[u8Ret], false);
  u8Ret += ssd1306_inverse_display(&pu8Dest[u8Ret], false);
  u8Ret += ssd1306_set_display_osc_freq(&pu8Dest[u8Ret], 0x08, 0x00);
  u8Ret += ssd1306_charge_pump_setting(&pu8Dest[u8Ret], true);
  u8Ret += ssd1306_set_display_on(&pu8Dest[u8Ret], true);
  u8Ret += ssd1306_set_page_page(&pu8Dest[u8Ret], 0U);
  u8Ret += ssd1306_set_hv_page_range(&pu8Dest[u8Ret], 0U, 3U);
  u8Ret += ssd1306_set_hv_column_range(&pu8Dest[u8Ret], 0U, 127U);

  return u8Ret;
}
